.TH man 1 "June 2016" "1.0" "cat man page"
.SH NAME
cat - Concatenate files
.SH SYNOPSIS
.B cat
[filename] [other filename]...
.SH DESCRIPTION
.B cat
concatenates the files listed as arguements and prints them one after another to standard output

.SH SEE ALSO
dd(1), sponge(1)
.SH AUTHOR
Jacob Adams <tookmund@gmail.com>
